algopedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import base

urlpatterns = [
    path('', include('cms.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', base.RedirectView.as_view(pattern_name="cms:login")),
    path('accounts/profile/', base.RedirectView.as_view(pattern_name="cms:index")),
]

cms/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from cms import views

app_name = 'cms'

urlpatterns = [
    # ホーム
    path('', views.index, name='index'),
    # ユーザー
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name="cms/pages/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page="cms:index"), name='logout'),
    path('user/<int:user_id>', views.user_page, name='user_page'),
    # 記事
    path('article/<int:article_id>', views.article_view, name='article_view'),
    path('article/add/', views.article_edit, name='article_add'),
    path('article/edit/<int:article_id>/', views.article_edit, name='article_edit'),
    path('article/del/<int:article_id>/', views.article_del, name='article_del'),
    # カテゴリ
    path('category/create', views.category_create, name='category_create'),
    # タグ
    path('tag/create', views.tag_create, name='tag_create'),
    # Ajax
    path('ajax/tag/add/<str:additional_tag>', views.tag_add_ajax, name='tag_add_ajax'),
    path('ajax/search/<int:page>', views.search_ajax, name='search_ajax'),
    path('ajax/fav/<int:article_id>/', views.fav_ajax, name='fav_ajax'),
    path('ajax/user_page/<int:user_id>/<int:page>', views.user_page_ajax, name='user_page_ajax'),
]

cms/forms.py
from django import forms

from cms.models import Tag, Category, Article
from users.models import User


class SignUpForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput)
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)
    model = User

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('このユーザー名は既に使用されています')
        return username

    def clean_password1(self):
        password = self.cleaned_data.get('password1')
        if password is None or \
                len(password) < 10 or \
                password.isupper() or \
                password.islower() or \
                password.isdecimal() or \
                password.isalpha():
            raise forms.ValidationError('パスワードは大文字・小文字・数字を含んだ 10 文字以上の英数字にしてください')
        if not password.isalnum():
            raise forms.ValidationError('英数字以外の文字は使用できません')
        return password

    def clean(self):
        super(SignUpForm, self).clean()
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and (password1 != password2):
            self.add_error('password2', '入力された 2 つのパスワードが一致していません')

    def save(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password1')
        new_user = User.objects.create_user(username=username)
        new_user.set_password(password)
        new_user.save()


class ArticleForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput)
    content = forms.CharField(widget=forms.Textarea)
    model = Article

    def clean_title(self):
        title = self.cleaned_data.get('title').strip()
        if len(title) == 0:
            raise forms.ValidationError('タイトルは必須です')
        if len(title) > 50:
            raise forms.ValidationError('タイトルは 50 文字以下にしてください')
        return title

    def clean_content(self):
        content = self.cleaned_data.get('content').strip()
        if len(content) == 0:
            raise forms.ValidationError('内容は必須です')
        return content

    def save(self):
        title = self.cleaned_data.get('title')
        content = self.cleaned_data.get('content')
        Article(title=title, content=content).save()


class TagForm(forms.Form):
    tag = forms.CharField(widget=forms.TextInput)
    model = Tag

    def clean_tag(self):
        tag = self.cleaned_data.get('tag').strip()
        if len(tag) > 15:
            raise forms.ValidationError('タグ名は 15 文字以下にして下さい')
        if Tag.exists(tag=tag):
            raise forms.ValidationError('このタグは既に存在します．')
        return tag

    def save(self):
        Tag(tag=self.cleaned_data.get('tag')).save()


class CategoryForm(forms.Form):
    category = forms.CharField(widget=forms.TextInput)
    model = Category

    def clean_category(self):
        category = self.cleaned_data.get('category').strip()
        if len(category) > 15:
            raise forms.ValidationError('タグ名は 15 文字以下にして下さい')
        if Category.exists(category=category):
            raise forms.ValidationError('このカテゴリは既に存在します')
        return category

    def save(self):
        Category(category=self.cleaned_data.get('category')).save()

cms/views.py
import json
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.core.paginator import PageNotAnInteger, Paginator, EmptyPage
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template import loader

# Create your views here.
from cms.forms import SignUpForm, TagForm, CategoryForm, ArticleForm
from cms.models import Article, Category, Tag, ArticleCategory, ArticleTags, Author, Favorite, ReadingHistory
from users.models import User


# ユーザー登録
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('cms:index')
    else:
        form = SignUpForm()
    return render(request, 'cms/pages/signup.html', dict(form=form))


# 記事のページ
def article_view(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    user: User = request.user
    # ログイン中かどうか
    if user.is_authenticated:
        # 閲覧履歴の更新 (なければ挿入)
        ReadingHistory.objects.update_or_create(article=article, user=user)
        # 既にお気に入りに設定しているか
        fav = Favorite.exists(article=article, user=user)
    else:
        fav = False
    context = {
        'article': article,
        'fav': fav,
    }
    return render(request, 'cms/pages/article.html', context)


# お気に入り登録 / 解除のトグルスイッチ
@login_required
def fav_ajax(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    has_created = Favorite.create_or_delete(article=article, user=request.user)
    article = get_object_or_404(Article, pk=article_id)
    return render(request, "cms/components/fav.html", dict(fav=has_created, article=article))


# 記事の新規作成 or 編集. article_id が None なら新規作成
@login_required
def article_edit(request, article_id=None):
    if article_id:
        article = get_object_or_404(Article, pk=article_id)
        # 記事の執筆者とログイン中のユーザーが異なる場合はログインページに飛ぶ
        if request.user != article.author.user:
            errors = ["編集権限がありません．記事作成者のアカウントにログインして下さい"]
            return render(request, "cms/pages/login.html", dict(errors=errors))
    if request.method == 'POST':
        # エラーメッセージ
        err = dict(title="", content="", category="", tag={})
        err_tpl = "cms/components/field_errors.html"
        forms = []

        # 入力内容
        title = request.POST.get("title")
        content = request.POST.get("content")
        category_name = request.POST.get('category')
        tag_names = request.POST.getlist('selected_tags')

        article_form = ArticleForm(data=dict(title=title, content=content))
        if article_form.is_valid():
            title = article_form.cleaned_data.get('title')
            content = article_form.cleaned_data.get('content')
        else:
            # エラーメッセージ
            err_title = "title" in article_form.errors and article_form.errors["title"]
            err_content = "content" in article_form.errors and article_form.errors["content"]
            err["title"] = loader.render_to_string(err_tpl, dict(errors=err_title))
            err["content"] = loader.render_to_string(err_tpl, dict(errors=err_content))

        category = Category.get_or_none(category=category_name)
        # カテゴリが存在しない場合は新規作成する
        if category is None:
            category_form = CategoryForm(data=dict(category=category_name))
            if category_form.is_valid():
                category_name = category_form.cleaned_data.get('category')
                category = Category(category=category_name)
            else:
                # エラーメッセージ
                err_category = "category" in category_form.errors and category_form.errors["category"]
                err["category"] = loader.render_to_string(err_tpl, dict(errors=err_category))
            forms.append(category_form)

        tags = []
        for tag_name in tag_names:
            tag = Tag.get_or_none(tag=tag_name)
            # タグが存在しない場合は新規作成する
            if tag is None:
                tag_form = TagForm(data=dict(tag=tag_name))
                if tag_form.is_valid():
                    tag_name = tag_form.cleaned_data.get('tag')
                    tag = Tag(tag=tag_name)
                else:
                    # エラーメッセージ
                    err_tag = "tag" in tag_form.errors and tag_form.errors['tag']
                    err["tag"][tag_name] = loader.render_to_string(err_tpl, dict(errors=err_tag))
                forms.append(tag_form)
            tags.append(tag)

        # 入力に何らかの不備があった場合 (status=1)
        if err["title"] or err["content"] or err["category"] or err["tag"]:
            err["tag"] = loader.render_to_string("cms/components/tag_errors.html", dict(errors=err["tag"]))
            return HttpResponse(
                json.dumps(dict(status=1, err=err)),
                content_type="text/javascript")

        for form in forms:
            form.save()

        # add
        if article_id is None:
            article = Article(title=title, content=content)
            article.save()
            ArticleCategory(article=article, category=category).save()
            for tag in tags:
                tag.save()
                ArticleTags(article=article, tag=tag).save()
            Author(article=article, user=request.user).save()
        # edit
        else:
            article = Article.objects.get(pk=article_id)
            article_category = article.articlecategory
            old_category = article_category.category
            new_category = Category.objects.get(category=category_name)

            # カテゴリが変更された場合はつじつま合わせをする必要がある
            if old_category != new_category:
                old_category.article_num -= 1
                old_category.save()
                article_category.category = new_category
                article_category.save()

            # タグ付けの更新
            for old_tag in ArticleTags.objects.filter(article=article).exclude(tag__in=tags):
                old_tag.delete()

            # 新しいタグ付け
            for new_tag in tags:
                if not ArticleTags.exists(article, new_tag):
                    ArticleTags(article=article, tag=new_tag).save()

            # 記事の情報を更新
            article.title = title
            article.content = content
            article.updated_at = datetime.now()
            article.save()

        # 入力が valid だったので status=0
        return HttpResponse(
            json.dumps(dict(status=0)),
            content_type="text/javascript")
    return init_article_form(request, article_id=article_id)


# 記事 form の初期化
def init_article_form(request, article_id=None):
    context = {
        "categories": Category.objects.all(),
        "tags": Tag.objects.all(),
    }
    if article_id is not None:
        context["article"] = get_object_or_404(Article, pk=article_id)
    return render(request, 'cms/pages/article_edit.html', context)


@login_required
def article_del(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    # 記事作成者でなければログイン画面へと遷移する
    if request.user != article.author.user:
        errors = ["削除権限がありません．記事作成者のアカウントにログインして下さい"]
        return render(request, "cms/pages/login.html", dict(errors=errors))
    article.delete()
    return redirect('cms:user_page', user_id=request.user.id)


def category_create(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            category = request.POST["category"]
            return render(request, 'cms/pages/create_category.html', dict(form=form, new_category=category))
    else:
        form = CategoryForm()
    return render(request, 'cms/pages/create_category.html', dict(form=form))


def tag_create(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            tag = request.POST["tag"]
            return render(request, 'cms/pages/create_tag.html', dict(form=form, new_tag=tag))
    else:
        form = TagForm()
    return render(request, 'cms/pages/create_tag.html', dict(form=form))


# ページング
def paginate_queryset(queryset, count, page=1):
    paginator = Paginator(queryset, count)
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    return page_obj


# トップ画面
def index(request):
    # デフォルトでは新着順に記事を表示
    post_list = Article.objects.all().order_by('-updated_at')
    page_obj = paginate_queryset(post_list, 10)
    context = {
        'post_list': page_obj.object_list,
        'page_obj': page_obj,
        'categories': Category.objects.all(),
        'tags': Tag.objects.all(),
    }
    return render(request, 'cms/pages/index.html', context)


# Ajax でタグを追加する (db への insert とは別)
def tag_add_ajax(request, additional_tag):
    return render(request, "cms/components/tag.html", dict(tag=additional_tag))


# Ajax で記事検索 or 並べ替えクエリを処理する
def search_ajax(request, page):
    # 検索結果を格納する QuerySet
    post_list = Article.objects.all()

    # 検索パラメータ取得
    username = request.GET.get("username")
    title = request.GET.get("title")
    category = request.GET.get("category")

    # 選択されたタグのリスト
    selected_tags = request.GET.getlist("selected_tags")

    # チェックボックスの入力 (リスト)
    checks = request.GET.getlist('check')

    # 検索 or 並び替え
    search_or_order = request.GET.get("search_or_order")

    if username:
        # 指定したユーザーが執筆した記事
        post_list = post_list.filter(author__user__username=username)

    if title:
        # 指定した文字列を連続部分文字列として含むタイトルを持つ記事 (LIKE)
        post_list = post_list.filter(title__icontains=title)

    if category:
        # 指定したカテゴリを持つ記事
        post_list = post_list.filter(articlecategory__category=category)

    if selected_tags:
        # 指定したいずれかのタグを持つ記事
        post_list = post_list.filter(articletags__tag__in=selected_tags)

    for check_val in checks:
        # ログイン中のユーザー

templates/cms/components/article_input.html
<div class="form-group row">
    <label for="id_content_form" class="col-sm-2 col-form-label">
        Content
    </label>
    <div class="col-sm-10">
        <textarea type="text"
                  class="form-control"
                  id="id_content_form"
                  name="content"
                  placeholder="内容"
                  rows="10"
        >{{ article.content }}</textarea>
    </div>
</div>

templates/cms/components/article_list.html
<div id="{{ htmls.search.id.result }}">
    <table class="table table-striped table-bordered" style="table-layout: fixed">
        <thead>
        <tr>
            <input type="hidden"
                   form="{{ htmls.search.id.form }}"
                   value="{{ search_or_order|default:"search" }}"
                   name="search_or_order"
                   id="{{ htmls.search.id.search_or_order }}">
            {% if not skip_author %}
                {% include "cms/components/article_list_th.html" with name="author__user__username" label="執筆者" %}
            {% endif %}
            {% include "cms/components/article_list_th.html" with name="title"      label="タイトル" %}
            {% include "cms/components/article_list_th.html" with name="fav_num"    label="お気に入り数" %}
            {% include "cms/components/article_list_th.html" with name="articlecategory__category" label="分野, タグ" %}
            {% include "cms/components/article_list_th.html" with name="updated_at" label="最終更新日時" %}
            {% if has_authority %}
                <th scope="col">操作</th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for article in post_list %}
            <tr>
                {% if not skip_author %}
                    <th scope="row">
                        <a href="{% url "cms:user_page" article.author.user.id %}" class="blink">
                            {{ article.author.user.username }}
                        </a>
                    </th>
                {% endif %}
                <td><a href="{% url 'cms:article_view' article.article_id %}">{{ article.title }}</a></td>
                <td>{{ article.fav_num }}</td>
                <td>
                    <div class="dropdown open">
                        <div class="dropdown-toggle"
                             data-toggle="dropdown"
                             aria-haspopup="true"
                             aria-expanded="false">
                            {{ article.articlecategory.category }}
                        </div>
                        <div class="dropdown-menu">
                            {% for tag in article.articletags_set.all %}
                                <span class="dropdown-item-text">{{ tag.tag }}</span>
                            {% endfor %}
                        </div>
                    </div>
                </td>
                <td>{{ article.updated_at }}</td>
                {% if has_authority %}
                    <td>
                        <button type="button"
                                class="btn btn-primary"
                                onclick="
                                        location.href='{% url 'cms:article_edit' article.article_id %}'
                                        "
                        >
                            編集
                        </button>
                        <button type="button"
                                class="btn btn-danger"
                                onclick="
                                        if (confirm('本当に削除しますか？')) {
                                        location.href='{% url "cms:article_del" article.article_id %}'
                                        }
                                        "
                        >
                            削除
                        </button>
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% include "cms/components/paging.html" %}
</div>

templates/cms/components/article_list_th.html
<th scope="col">
    <div class="container-fluid">
        <div class="row justify-content-between">
            <div class="align-self-center">
                {% with default_label=name|capfirst %}
                {{ label|default:default_label }}
                {% endwith %}
            </div>
            <div class="btn-group-vertical">
                {% include "cms/components/order_button.html" with name=name asc=True %}
                {% include "cms/components/order_button.html" with name=name asc=False %}
            </div>
        </div>
    </div>
</th>

templates/cms/components/category_selector.html
<div class="form-group row">
    <label for="{{ htmls.category.id.input }}" class="col-md-2 col-form-label">
        Category
    </label>
    <input type="text"
           name="category"
           autocomplete="on"
           list="{{ htmls.category.id.datalist }}"
           class="col-md-9 form-control"
           value="{{ article.articlecategory.category.category }}"
           placeholder="分野"
           id="{{ htmls.category.id.input }}">
    <datalist id="{{ htmls.category.id.datalist }}">
        {% for category in categories %}
            <option value="{{ category.category }}" label="記事数: {{ category.article_num }}"></option>
        {% endfor %}
    </datalist>
</div>

templates/cms/components/fav.html
{% if request.user.is_authenticated %}
    <button type="button"
            class="btn btn-sm btn-outline-{{ fav|yesno:"danger,success" }}"
            id="{{ htmls.fav.id.toggle_button }}">
        お気に入り{{ fav|yesno:"解除,登録" }}
    </button>
{% endif %}
<span style="font-size: 0.5em">★: {{ article.fav_num }}</span>

templates/cms/components/field_errors.html
{% if errors %}
    <div class="alert alert-warning" role="alert">
        <ul>{% for err in errors %}<li>{{ err }}</li>{% endfor %}</ul>
    </div>
{% endif %}

templates/cms/components/form_errors.html
{% if form.errors %}
    <div class="alert alert-warning" role="alert">
        <ul>
            {% for errors in form.errors.values %}
                {% for err in errors %}
                    <li>{{ err }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
    </div>
{% endif %}

templates/cms/components/order_button.html
<button type="submit"
        class="btn btn-sm btn-light"
        style="padding:0"
        form="{{ htmls.search.id.form }}"
        onclick="$('#{{ htmls.search.id.search_or_order }}').val('{{ asc|yesno:",-"|add:name }}')"
>{% if asc %}&and;{% else %}&or;{% endif %}
</button>

templates/cms/components/paging.html
<ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item">
            <button class="page-link"
                    value="{{ page_obj.previous_page_number }}"
                    name="{{ htmls.paging.name.button }}"
                    aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </button>
        </li>
    {% endif %}
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <li class="page-item active">
                <span class="page-link">
                    {{ num }}
                    <span class="sr-only">(current)</span>
                </span>
            </li>
        {% else %}
            <li class="page-item">
                <button class="page-link"
                        value="{{ num }}"
                        name="{{ htmls.paging.name.button }}"
                >{{ num }}</button>
            </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item">
            <button class="page-link"
                    value="{{ page_obj.next_page_number }}"
                    name="{{ htmls.paging.name.button }}"
                    aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </button>
        </li>
    {% endif %}
</ul>

templates/cms/components/search.html
<div class="card mtb">
    <div class="card-header"><h2>記事検索</h2></div>
    <div class="card-body">
        <form action="" method="get" id="{{ htmls.search.id.form }}">
            {% csrf_token %}
            {% include "cms/components/text_input.html" with name="username" value=article.author.user.username placeholder="執筆者 ('@'は不要です)" %}
            {% include "cms/components/title_input.html" %}
            {% include "cms/components/category_selector.html" %}
            {% include "cms/components/tag_selector.html" %}
            {% if request.user.is_authenticated %}
                {% include "cms/components/search_checkbox.html" with value="author" statement="自分の書いた記事のみを表示する" %}
                {% include "cms/components/search_checkbox.html" with value="fav" statement="お気に入りの記事のみを表示する" %}
                {% include "cms/components/search_checkbox.html" with value="read" statement="最近閲覧した記事のみを表示する" %}
            {% endif %}
            <div class="form-group row justify-content-center">
                <button type="submit"
                        class="col-md-8 btn btn-info"
                        name="search"
                        onclick="$('#{{ htmls.search.id.search_or_order }}').val('search')">
                    検索
                </button>
            </div>
            <div class="form-group row justify-content-center">
                <button type="reset"
                        class="col-md-8 btn btn-secondary"
                        name="search"
                        onclick="$(tag_button).each(function (i, o) {del_tag(o.value)});">
                    検索条件をリセット
                </button>
            </div>
        </form>
    </div>
</div>
<div class="mtb">
    <h2>検索結果</h2>
    {% include "cms/components/article_list.html" %}
</div>

templates/cms/components/tag.html
<li class="col-sm-2 shadow p-2 mb-2 rounded list-group-item-info" value="{{ tag }}">
    {{ tag }}
    <button type="button"
            class="close"
            aria-label="閉じる"
            value="{{ tag }}"
            name="{{ htmls.tag.name.deselect_button }}"
    ><span aria-hidden="true">&times;</span></button>
</li>

templates/cms/components/tag_selector.html
<div class="form-group row">
    <label for="{{ htmls.tag.id.input }}" class="col-md-2 col-form-label">
        Tag
    </label>
    <div class="col-md-9" style="padding-left: 0; padding-right: 0">
        <ul class="row"
            id="{{ htmls.tag.id.selected_tags }}"
            style="list-style: none">
            {% for init_tag in article.get_tags %}
                {% include "cms/components/tag.html" with tag=init_tag.tag %}
            {% endfor %}
        </ul>
        <div class="input-group">
            <input type="text"
                   autocomplete="on"
                   list="{{ htmls.tag.id.datalist }}"
                   class="form-control"
                   placeholder="タグ"
                   id="{{ htmls.tag.id.input }}">
            <div class="input-group-append">
                <button type="button"
                        class="input-group-text"
                        id="{{ htmls.tag.id.select_button }}"
                >Add Tag</button>
            </div>
            <datalist id="{{ htmls.tag.id.datalist }}">
                {% for tag in tags %}
                    <option label="記事数: {{ tag.article_num }}"
                            value="{{ tag.tag }}"
                            {% if tag in init_selected_tags %}
                            disabled="disabled"
                            {% endif %}
                    ></option>
                {% endfor %}
            </datalist>
        </div>
    </div>
</div>

templates/cms/components/text_input.html
<div class="form-group row">
    <label for="id_{{ name }}_text_input" class="col-md-2 col-form-label">
        {% with default_label=name|capfirst %}
        {{ label|default:default_label }}
        {% endwith %}
    </label>
    <input type="text"
           name="{{ name }}"
           {{ autofocus|default:False|yesno:"autofocus," }}
           {{ required|default:False|yesno:"required," }}
           class="col-md-9 form-control"
           value="{{ value }}"
           placeholder="{{ placeholder }}"
           id="id_{{ name }}_text_input">
</div>

templates/cms/components/title_input.html
{% include "cms/components/text_input.html" with name="title" value=article.title placeholder="記事のタイトル" %}