algopedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import base

urlpatterns = [
    path('', include('cms.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', base.RedirectView.as_view(pattern_name="cms:login")),
    path('accounts/profile/', base.RedirectView.as_view(pattern_name="cms:index")),
]

cms/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from cms import views

app_name = 'cms'

urlpatterns = [
    # ホーム
    path('', views.index, name='index'),
    # ユーザー
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name="cms/pages/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page="cms:index"), name='logout'),
    path('user/<int:user_id>', views.user_page, name='user_page'),
    # 記事
    path('article/<int:article_id>', views.article_view, name='article_view'),
    path('article/add/', views.article_edit, name='article_add'),
    path('article/edit/<int:article_id>/', views.article_edit, name='article_edit'),
    path('article/del/<int:article_id>/', views.article_del, name='article_del'),
    # カテゴリ
    path('category/create', views.category_create, name='category_create'),
    # タグ
    path('tag/create', views.tag_create, name='tag_create'),
    # Ajax
    path('ajax/tag/add/<str:additional_tag>', views.tag_add_ajax, name='tag_add_ajax'),
    path('ajax/search/<int:page>', views.search_ajax, name='search_ajax'),
    path('ajax/fav/<int:article_id>/', views.fav_ajax, name='fav_ajax'),
    path('ajax/user_page/<int:user_id>/<int:page>', views.user_page_ajax, name='user_page_ajax'),
]

cms/forms.py
from django import forms

from cms.models import Tag, Category, Article
from users.models import User


class SignUpForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput)
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)
    model = User

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('このユーザー名は既に使用されています')
        return username

    def clean_password1(self):
        password = self.cleaned_data.get('password1')
        if password is None or \
                len(password) < 10 or \
                password.isupper() or \
                password.islower() or \
                password.isdecimal() or \
                password.isalpha():
            raise forms.ValidationError('パスワードは大文字・小文字・数字を含んだ 10 文字以上の英数字にしてください')
        if not password.isalnum():
            raise forms.ValidationError('英数字以外の文字は使用できません')
        return password

    def clean(self):
        super(SignUpForm, self).clean()
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and (password1 != password2):
            self.add_error('password2', '入力された 2 つのパスワードが一致していません')

    def save(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password1')
        new_user = User.objects.create_user(username=username)
        new_user.set_password(password)
        new_user.save()


class ArticleForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput)
    content = forms.CharField(widget=forms.Textarea)
    model = Article

    def clean_title(self):
        title = self.cleaned_data.get('title').strip()
        if len(title) == 0:
            raise forms.ValidationError('タイトルは必須です')
        if len(title) > 50:
            raise forms.ValidationError('タイトルは 50 文字以下にしてください')
        return title

    def clean_content(self):
        content = self.cleaned_data.get('content').strip()
        if len(content) == 0:
            raise forms.ValidationError('内容は必須です')
        return content

    def save(self):
        title = self.cleaned_data.get('title')
        content = self.cleaned_data.get('content')
        Article(title=title, content=content).save()


class TagForm(forms.Form):
    tag = forms.CharField(widget=forms.TextInput)
    model = Tag

    def clean_tag(self):
        tag = self.cleaned_data.get('tag').strip()
        if len(tag) > 15:
            raise forms.ValidationError('タグ名は 15 文字以下にして下さい')
        if Tag.exists(tag=tag):
            raise forms.ValidationError('このタグは既に存在します．')
        return tag

    def save(self):
        Tag(tag=self.cleaned_data.get('tag')).save()


class CategoryForm(forms.Form):
    category = forms.CharField(widget=forms.TextInput)
    model = Category

    def clean_category(self):
        category = self.cleaned_data.get('category').strip()
        if len(category) > 15:
            raise forms.ValidationError('タグ名は 15 文字以下にして下さい')
        if Category.exists(category=category):
            raise forms.ValidationError('このカテゴリは既に存在します')
        return category

    def save(self):
        Category(category=self.cleaned_data.get('category')).save()

cms/views.py
import json
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.core.paginator import PageNotAnInteger, Paginator, EmptyPage
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template import loader

# Create your views here.
from cms.forms import SignUpForm, TagForm, CategoryForm, ArticleForm
from cms.models import Article, Category, Tag, ArticleCategory, ArticleTags, Author, Favorite, ReadingHistory
from users.models import User


# ユーザー登録
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('cms:index')
    else:
        form = SignUpForm()
    return render(request, 'cms/pages/signup.html', dict(form=form))


# 記事のページ
def article_view(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    user: User = request.user
    # ログイン中かどうか
    if user.is_authenticated:
        # 閲覧履歴の更新 (なければ挿入)
        ReadingHistory.objects.update_or_create(article=article, user=user)
        # 既にお気に入りに設定しているか
        fav = Favorite.exists(article=article, user=user)
    else:
        fav = False
    context = {
        'article': article,
        'fav': fav,
    }
    return render(request, 'cms/pages/article.html', context)


# お気に入り登録 / 解除のトグルスイッチ
@login_required
def fav_ajax(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    has_created = Favorite.create_or_delete(article=article, user=request.user)
    article = get_object_or_404(Article, pk=article_id)
    return render(request, "cms/components/fav.html", dict(fav=has_created, article=article))


# 記事の新規作成 or 編集. article_id が None なら新規作成
@login_required
def article_edit(request, article_id=None):
    if article_id:
        article = get_object_or_404(Article, pk=article_id)
        # 記事の執筆者とログイン中のユーザーが異なる場合はログインページに飛ぶ
        if request.user != article.author.user:
            errors = ["編集権限がありません．記事作成者のアカウントにログインして下さい"]
            return render(request, "cms/pages/login.html", dict(errors=errors))
    if request.method == 'POST':
        # エラーメッセージ
        err = dict(title="", content="", category="", tag={})
        err_tpl = "cms/components/field_errors.html"
        forms = []

        # 入力内容
        title = request.POST.get("title")
        content = request.POST.get("content")
        category_name = request.POST.get('category')
        tag_names = request.POST.getlist('selected_tags')

        article_form = ArticleForm(data=dict(title=title, content=content))
        if article_form.is_valid():
            title = article_form.cleaned_data.get('title')
            content = article_form.cleaned_data.get('content')
        else:
            # エラーメッセージ
            err_title = "title" in article_form.errors and article_form.errors["title"]
            err_content = "content" in article_form.errors and article_form.errors["content"]
            err["title"] = loader.render_to_string(err_tpl, dict(errors=err_title))
            err["content"] = loader.render_to_string(err_tpl, dict(errors=err_content))

        category = Category.get_or_none(category=category_name)
        # カテゴリが存在しない場合は新規作成する
        if category is None:
            category_form = CategoryForm(data=dict(category=category_name))
            if category_form.is_valid():
                category_name = category_form.cleaned_data.get('category')
                category = Category(category=category_name)
            else:
                # エラーメッセージ
                err_category = "category" in category_form.errors and category_form.errors["category"]
                err["category"] = loader.render_to_string(err_tpl, dict(errors=err_category))
            forms.append(category_form)

        tags = []
        for tag_name in tag_names:
            tag = Tag.get_or_none(tag=tag_name)
            # タグが存在しない場合は新規作成する
            if tag is None:
                tag_form = TagForm(data=dict(tag=tag_name))
                if tag_form.is_valid():
                    tag_name = tag_form.cleaned_data.get('tag')
                    tag = Tag(tag=tag_name)
                else:
                    # エラーメッセージ
                    err_tag = "tag" in tag_form.errors and tag_form.errors['tag']
                    err["tag"][tag_name] = loader.render_to_string(err_tpl, dict(errors=err_tag))
                forms.append(tag_form)
            tags.append(tag)

        # 入力に何らかの不備があった場合 (status=1)
        if err["title"] or err["content"] or err["category"] or err["tag"]:
            err["tag"] = loader.render_to_string("cms/components/tag_errors.html", dict(errors=err["tag"]))
            return HttpResponse(
                json.dumps(dict(status=1, err=err)),
                content_type="text/javascript")

        for form in forms:
            form.save()

        # add
        if article_id is None:
            article = Article(title=title, content=content)
            article.save()
            ArticleCategory(article=article, category=category).save()
            for tag in tags:
                tag.save()
                ArticleTags(article=article, tag=tag).save()
            Author(article=article, user=request.user).save()
        # edit
        else:
            article = Article.objects.get(pk=article_id)
            article_category = article.articlecategory
            old_category = article_category.category
            new_category = Category.objects.get(category=category_name)

            # カテゴリが変更された場合はつじつま合わせをする必要がある
            if old_category != new_category:
                old_category.article_num -= 1
                old_category.save()
                article_category.category = new_category
                article_category.save()

            # タグ付けの更新
            for old_tag in ArticleTags.objects.filter(article=article).exclude(tag__in=tags):
                old_tag.delete()

            # 新しいタグ付け
            for new_tag in tags:
                if not ArticleTags.exists(article, new_tag):
                    ArticleTags(article=article, tag=new_tag).save()

            # 記事の情報を更新
            article.title = title
            article.content = content
            article.updated_at = datetime.now()
            article.save()

        # 入力が valid だったので status=0
        return HttpResponse(
            json.dumps(dict(status=0)),
            content_type="text/javascript")
    return init_article_form(request, article_id=article_id)


# 記事 form の初期化
def init_article_form(request, article_id=None):
    context = {
        "categories": Category.objects.all(),
        "tags": Tag.objects.all(),
    }
    if article_id is not None:
        context["article"] = get_object_or_404(Article, pk=article_id)
    return render(request, 'cms/pages/article_edit.html', context)


@login_required
def article_del(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    # 記事作成者でなければログイン画面へと遷移する
    if request.user != article.author.user:
        errors = ["削除権限がありません．記事作成者のアカウントにログインして下さい"]
        return render(request, "cms/pages/login.html", dict(errors=errors))
    article.delete()
    return redirect('cms:user_page', user_id=request.user.id)


def category_create(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            category = request.POST["category"]
            return render(request, 'cms/pages/create_category.html', dict(form=form, new_category=category))
    else:
        form = CategoryForm()
    return render(request, 'cms/pages/create_category.html', dict(form=form))


def tag_create(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            tag = request.POST["tag"]
            return render(request, 'cms/pages/create_tag.html', dict(form=form, new_tag=tag))
    else:
        form = TagForm()
    return render(request, 'cms/pages/create_tag.html', dict(form=form))


# ページング
def paginate_queryset(queryset, count, page=1):
    paginator = Paginator(queryset, count)
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    return page_obj


# トップ画面
def index(request):
    # デフォルトでは新着順に記事を表示
    post_list = Article.objects.all().order_by('-updated_at')
    page_obj = paginate_queryset(post_list, 10)
    context = {
        'post_list': page_obj.object_list,
        'page_obj': page_obj,
        'categories': Category.objects.all(),
        'tags': Tag.objects.all(),
    }
    return render(request, 'cms/pages/index.html', context)


# Ajax でタグを追加する (db への insert とは別)
def tag_add_ajax(request, additional_tag):
    return render(request, "cms/components/tag.html", dict(tag=additional_tag))


# Ajax で記事検索 or 並べ替えクエリを処理する
def search_ajax(request, page):
    # 検索結果を格納する QuerySet
    post_list = Article.objects.all()

    # 検索パラメータ取得
    username = request.GET.get("username")
    title = request.GET.get("title")
    category = request.GET.get("category")

    # 選択されたタグのリスト
    selected_tags = request.GET.getlist("selected_tags")

    # チェックボックスの入力 (リスト)
    checks = request.GET.getlist('check')

    # 検索 or 並び替え
    search_or_order = request.GET.get("search_or_order")

    if username:
        # 指定したユーザーが執筆した記事
        post_list = post_list.filter(author__user__username=username)

    if title:
        # 指定した文字列を連続部分文字列として含むタイトルを持つ記事 (LIKE)
        post_list = post_list.filter(title__icontains=title)

    if category:
        # 指定したカテゴリを持つ記事
        post_list = post_list.filter(articlecategory__category=category)

    if selected_tags:
        # 指定したいずれかのタグを持つ記事
        post_list = post_list.filter(articletags__tag__in=selected_tags)

    for check_val in checks:
        # ログイン中のユーザー

templates/cms/pages/article.html
{% extends "cms/pages/base.html" %}

{% block content %}
    <div class="card mtb">
        <div class="card-header">
            <div class="container">
                <p class="text-right">執筆者:
                    <a href="{% url "cms:user_page" article.author.user.id %}">@{{ article.author.user }}</a>
                </p>
                <p class="text-right">作成: {{ article.created_at }}</p>
                <p class="text-right">更新: {{ article.updated_at }}</p>
            </div>
        </div>
        <div class="card-body">
            <div class="row justify-content-between">
                <div class="col-md-10">
                    <h2>{{ article.title }}
                        <span id="{{ htmls.fav.id.info }}">{% include "cms/components/fav.html" %}</span>
                    </h2>
                </div>
                <div class="col-md-2" style="padding-left: 0; padding-right: 0">
                    {% if article.author.user == request.user %}
                        <button type="button"
                                class="btn btn-sm btn-outline-dark"
                                onclick="location.href='{% url "cms:article_edit" article.article_id %}'">
                            記事を編集する
                        </button>
                    {% endif %}
                </div>
            </div>

            <div class="row card-subtitle text-sm text-muted container mb-2">
                分野: {{ article.articlecategory.category.category }}
            </div>
            <div class="row card-subtitle text-sm text-muted container mb-2">
                タグ:
                {% for tag_name in article.get_tag_names %}
                    {{ tag_name }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </div>
            {{ article.content }}
        </div>
    </div>
    <div class="form-group row justify-content-center mtb">
        <button type="button"
                class="col-md-6 btn btn-secondary"
                onclick="history.go(-1);">
            戻る
        </button>
    </div>
{% endblock %}

{% block extra_js %}
    <script type="text/javascript">
        $(document).on('click', "#{{ htmls.fav.id.toggle_button }}", function () {
            $.ajax({
                url: "{% url 'cms:fav_ajax' article_id=article.article_id|default:0 %}",
                method: "GET",
                timeout: 10000,
            }).done(function (data) {
                $("#{{ htmls.fav.id.info }}").html(data)
            });
        })
    </script>
{% endblock %}

templates/cms/pages/article_edit.html
{% extends "cms/pages/base.html" %}

{% block title %}記事の{{ article|yesno:"編集,追加" }}{% endblock title %}

{% block content %}
    <h4 class="mt-4 mb-5 border-bottom">記事の{{ article|yesno:"編集,追加" }}</h4>
    {% url 'cms:article_edit' article_id=article.article_id as url_edit %}
    {% url 'cms:article_add' as url_add %}
    <form action="{% if article %}{{ url_edit }}{% else %}{{ url_add }}{% endif %}"
          method="post"
          id="{{ htmls.article.id.form }}">
        {% csrf_token %}
        <div id="id_title_err"></div>
        {% include "cms/components/title_input.html" %}
        <div id="id_category_err"></div>
        {% include "cms/components/category_selector.html" %}
        <div id="id_tag_err"></div>
        {% include "cms/components/tag_selector.html" %}
        <div id="id_content_err"></div>
        {% include "cms/components/article_input.html" %}
        <div class="form-group row justify-content-center">
            <button type="submit" class="col-md-6 btn btn-primary">保存</button>
        </div>
    </form>
    <div class="form-group row justify-content-center">
        <button type="button"
                class="col-md-6 btn btn-secondary"
                onclick="history.go(-1);"
        >保存せずに戻る
        </button>
    </div>
{% endblock content %}

{% block extra_js %}
    {% include "cms/js/tag_selector.js.html" %}
    <script type="text/javascript">
        $('#{{ htmls.article.id.form }}').submit(function (event) {
            // default の動作を止める
            event.preventDefault();
            // form 情報
            const form = $(this);
            // 選択したタグの情報を集めて form に追加する
            const $inputs = get_tag_inputs();
            $inputs.forEach(function ($input) {
                form.append($input)
            })
            $.ajax({
                url: form.prop("action"),
                method: form.prop("method"),
                data: form.serialize(),
                timeout: 10000,
                dataType: "text",
            }).done(function (data) {
                console.log(data)
                const dict = $.parseJSON(data)
                console.log(dict)
                if (dict.status === 0) {
                    history.go(-1)
                    {#location.href = "{% url "cms:user_page" user_id=request.user.id %}"#}
                } else if (dict.status === 1) {
                    const errors = dict.err
                    $("#id_title_err").html(errors.title)
                    $("#id_category_err").html(errors.category)
                    $("#id_tag_err").html(errors.tag)
                    $("#id_content_err").html(errors.content)
                } else {
                    alert("不明なエラー")
                }
            })
            $inputs.forEach(function ($input) {
                $input.remove()
            })
        })
    </script>
{% endblock %}

templates/cms/pages/base.html
{% load i18n static %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static 'cms/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'cms/css/bootstrap.min.css' %}">

    {% block extra_css %}{% endblock %}

    <title>{% block title %}Algopedia{% endblock %}</title>

</head>
<body>
{% include "cms/components/nav.html" %}
<div class="container">
    {% block content %}
        {{ content }}
    {% endblock %}
</div>
<script src="{% static 'cms/js/jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'cms/js/popper.min.js' %}"></script>
<script src="{% static 'cms/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'cms/js/custom.js' %}"></script>
{# MathJax #}
<script type="text/x-mathjax-config">
    MathJax.Hub.Config({ tex2jax: { inlineMath: [['$','$'], ["\\(","\\)"]] } });
</script>
<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_CHTML">
</script>
<meta http-equiv="X-UA-Compatible" CONTENT="IE=EmulateIE7"/>
{# MathJax ここまで#}
{% block extra_js %}{% endblock %}
</body>
</html>

templates/cms/pages/create_category.html
{% extends "cms/pages/base.html" %}

{% block content %}
    <div class="card">
        <div class="card-header"><h3>新規カテゴリ作成</h3></div>
        <div class="card-body">
            <form action="" method="post">
                {% csrf_token %}
                {% include "cms/components/form_errors.html" %}
                {% if new_category %}
                    <div class="alert alert-success" role="alert">
                        カテゴリ "{{ new_category }}" を追加しました
                    </div>
                {% endif %}
                {% include "cms/components/text_input.html" with name="category" autofocus=True required=True %}
                <div class="form-group row justify-content-center">
                    <button type="submit" class="col-md-6 btn btn-primary">Create</button>
                </div>
            </form>
            <div class="form-group row justify-content-center">
                <button type="button"
                        class="col-md-6 btn btn-secondary"
                        onclick="location.href='{% url 'cms:index' %}'"
                >ホームに戻る</button>
            </div>
        </div>
    </div>
{% endblock %}

templates/cms/pages/create_tag.html
{% extends "cms/pages/base.html" %}

{% block content %}
    <div class="card">
        <div class="card-header">
            <h3>新規タグ作成</h3>
        </div>
        <div class="card-body">
            <form action="" method="post">
                {% csrf_token %}
                {% include "cms/components/form_errors.html" %}
                {% if new_tag %}
                    <div class="alert alert-success" role="alert">
                        タグ "{{ new_tag }}" を追加しました
                    </div>
                {% endif %}
                {% include "cms/components/text_input.html" with name="tag" autofocus=True required=True %}
                <div class="form-group row justify-content-center">
                    <button type="submit" class="col-md-6 btn btn-primary">Create</button>
                </div>
            </form>
            <div class="form-group row justify-content-center">
                <button type="button"
                        class="col-md-6 btn btn-secondary"
                        onclick="location.href='{% url 'cms:index' %}'"
                >ホームに戻る</button>
            </div>
        </div>
    </div>
{% endblock %}

templates/cms/pages/index.html
{% extends "cms/pages/base.html" %}

{% block content %}
    {% include "cms/components/search.html" %}
{% endblock content %}

{% block extra_js %}
    {% include "cms/js/tag_selector.js.html" %}
    <script type="text/javascript">
        const $search_form = $('#{{ htmls.search.id.form }}')
        const $search_result = $("#{{ htmls.search.id.result }}")
        const paging_button = "button[name='{{ htmls.paging.name.button }}']"

        // 検索結果の更新
        $search_form.submit(function (event) {
            // default の動作を止める
            event.preventDefault();
            // 選択したタグの情報を集めて form に追加する
            const $inputs = get_tag_inputs();
            $inputs.forEach(function ($input) {
                $search_form.append($input)
            })
            // Ajax で更新
            $.ajax({
                url: "{% url 'cms:search_ajax' 1 %}",
                method: $search_form.prop("method"),
                // 良い感じにデータ整形をしてもらう
                data: $search_form.serialize(),
                timeout: 10000,
                dataType: "text",
            }).done(function (data) {
                $search_result.html(data);
            })
            // 行儀よく
            $inputs.forEach(function ($input) {
                $input.remove()
            })
        })
        // ページ選択
        $(document).on('click', paging_button, function () {
            // 選択したタグの情報
            const $inputs = get_tag_inputs();
            $inputs.forEach(function ($input) {
                $search_form.append($input)
            });
            const next_page = $(this).val()
            $.ajax({
                url: "{% url 'cms:search_ajax' 0 %}".replace("0", next_page),
                method: $search_form.prop("method"),
                data: $search_form.serialize(),
                timeout: 10000,
                dataType: "text",
            }).done(function (data) {
                $search_result.html(data);
            });
            $inputs.forEach(function ($input) {
                $input.remove()
            })
        })
    </script>
{% endblock %}

templates/cms/pages/login.html
{% extends "cms/pages/base.html" %}

{% block content %}
    <div class="card">
        <div class="card-header"><h3>ログイン</h3></div>
        <div class="card-body">
            {% if errors %}
                <div class="alert alert-danger" role="alert">
                    <ul>
                        {% for err in errors %}
                            <li>{{ err }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            <form action="{% url 'cms:login' %}" method="post">
                {% csrf_token %}
                {% include "cms/components/text_input.html" with name="username" label="ユーザー名" autofocus=True required=True %}
                {% include "cms/components/password_input.html" with name="password" label="パスワード" %}
                <div class="form-group row justify-content-center">
                    <button type="submit" class="col-md-6 btn btn-primary">Login</button>
                </div>
            </form>
            <p>まだユーザー登録してない場合は <a href="{% url 'cms:signup' %}">Sign Up</a> からユーザー登録をしてください</p>
        </div>
    </div>
{% endblock %}

templates/cms/pages/signup.html
{% extends "cms/pages/base.html" %}

{% block content %}
    <div class="card">
        <div class="card-header"><h3>ユーザー登録</h3></div>
        <div class="card-body">
            {% include "cms/components/form_errors.html" with form=form %}
            <form action="{% url 'cms:signup' %}" method="post">
                {% csrf_token %}
                {% include "cms/components/text_input.html" with name="username" label="ユーザー名" autofocus=True required=True %}
                {% include "cms/components/password_input.html" with name="password1" label="パスワード" %}
                {% include "cms/components/password_input.html" with name="password2" label="パスワード (再入力)" %}
                <div class="form-group row justify-content-center">
                    <button type="submit" class="col-md-6 btn btn-primary">Sign Up</button>
                </div>
            </form>
            <p>既にユーザー登録が済んでいる場合は <a href="{% url 'cms:login' %}">Sign In</a> からログインしてください</p>
        </div>
    </div>
{% endblock %}

templates/cms/pages/user_page.html
{% extends "cms/pages/base.html" %}

{% block content %}
    <div class="mtb">
        {% if user.is_superuser %}
            <span class="badge badge-danger">Admin</span>
        {% endif %}
        <h2>@{{ user.username }} のページ</h2>
    </div>

    {# dummy form #}
    <form action="" method="get" id="{{ htmls.search.id.form }}">{% csrf_token %}</form>

    <div class="row">
        <div class="col-md-3">
            <dl class="dl-horizontal">
                <dt class="col-sm-12">ユーザー名</dt>
                <dd class="col-sm-12">@{{ user.username }}</dd>

                <dt class="col-sm-12">登録日時</dt>
                <dd class="col-sm-12">{{ user.date_joined }}</dd>

                <dt class="col-sm-12">お気に入りされた数</dt>
                <dd class="col-sm-12">{{ user.liked_num }}</dd>

                <dt class="col-sm-12">書いた記事の数</dt>
                <dd class="col-sm-12">{{ user.author_articles.count }}</dd>

                <dt class="col-sm-12">分野</dt>
                <dd class="col-sm-12">
                    <ul>
                        {% for category_count in user.category_counts %}
                            <li>{{ category_count.category }}: {{ category_count.count }}</li>
                        {% endfor %}
                    </ul>
                </dd>

                <dt class="col-sm-12">タグ</dt>
                <dd class="col-sm-12">
                    <ul>
                        {% for tag_count in user.tag_counts %}
                            <li>{{ tag_count.tag }}: {{ tag_count.count }}</li>
                        {% endfor %}
                    </ul>
                </dd>
            </dl>
        </div>
        <div class="col-md-9">
            <h3>執筆記事一覧</h3>
            {% include "cms/components/article_list.html" %}
        </div>
    </div>
{% endblock %}

{% block extra_js %}
    <script type="text/javascript">
        const $search_form = $('#{{ htmls.search.id.form }}')
        const $search_result = $("#{{ htmls.search.id.result }}")
        const paging_button = "button[name='{{ htmls.paging.name.button }}']"

        // 更新
        $search_form.submit(function (event) {
            event.preventDefault();
            $.ajax({
                url: "{% url 'cms:user_page_ajax' user.id 1 %}",
                method: $search_form.prop("method"),
                data: $search_form.serialize(),
                timeout: 10000,
                dataType: "text",
            }).done(function (data) {
                $search_result.html(data);
            })
        })
        // ページ選択
        $(document).on('click', paging_button, function () {
            const next_page = $(this).val()
            $.ajax({
                url: "{% url 'cms:user_page_ajax' user.id 0 %}".replace("0", next_page),
                method: $search_form.prop("method"),
                data: $search_form.serialize(),
                timeout: 10000,
                dataType: "text",
            }).done(function (data) {
                $search_result.html(data);
            });
        })
    </script>
{% endblock %}